### ISSUE TITLE
Create Rough Draft of the Proposal

### ISSUE THREAD

**Issue by Slyssy** [Slyssy/Project-2-Job_Costing_App#3]

**Comment by michaeldonatucci9** [comment]
[Project Management Proposal for Job Costing of Jobs bid.docx](https://github.com/Slyssy/Project-2-Job_Costing_App/files/5498745/Project.Management.Proposal.for.Job.Costing.of.Jobs.bid.docx)

**Comment by Slyssy** [comment]
Rough draft was submitted by Michael. The official proposal was entered as part of the ReadMe file.
